### ISSUE TITLE
[BUG] Issue when trying to load a pandas dataframe with columns with dtype: datetime64[ns]

### ISSUE THREAD

**Issue by rdodev** [Kanaries/pygwalker#111]
I'm trying to load pygwalker a dataframe with columns which are of  `dtype: datetime64[ns]`. When I  run `pyg.walk(df)` I get the following error:
```
[E 13:54:21.599 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/home/user/.virtualenvs/theo/lib/python3.10/site-packages/tornado/iostream.py", line 695, in _handle_events
        self._handle_write()
      File "/home/user/.virtualenvs/theo/lib/python3.10/site-packages/tornado/iostream.py", line 965, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/home/user/.virtualenvs/theo/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/user/.virtualenvs/theo/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 192, in _handle_events
    handler_func(fileobj, events)
  File "/home/user/.virtualenvs/theo/lib/python3.10/site-packages/tornado/iostream.py", line 695, in _handle_events
    self._handle_write()
  File "/home/user/.virtualenvs/theo/lib/python3.10/site-packages/tornado/iostream.py", line 965, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/home/user/.virtualenvs/theo/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
```
~~If I cast those columns to strings, it "works", but then I lose the ability to filter by date ranges and any other features associated with dates.~~ 

Unfortunately, just tried different ways and it just crashes regardless of column dtypes.

dataframe shape: 6435 rows × 8 columns

Environment:
OS: Ubuntu 22.04
Python: 3.10.6
Jupyter notebook: 6.5.4

**Comment by rdodev** [comment]
Confirmed it happens in docker container as well.

**Comment by Asm-Def** [comment]
hello, what's the version of `pygwalker`?

The development is mainly in JupyterLab, so there might be some incompatibilities in legacy notebooks.

**Comment by rdodev** [comment]
@Asm-Def can confirm that with Jupyter Lab this works as expected. I'm wondering why it won't work with latest version of notebook 🤔

**Comment by Asm-Def** [comment]
> @Asm-Def can confirm that with Jupyter Lab this works as expected. I'm wondering why it won't work with latest version of notebook 🤔

I'm not sure, but might because the displayed HTML output exceeds the default size limit of the stream buffer of NotebookApp.
