### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 511737: character maps to <undefined>

### ISSUE THREAD

**Issue by ObservedObserver** [Kanaries/pygwalker#12]
This is an issue from [reddit](https://www.reddit.com/r/datascience/comments/117bptb/comment/j9cb6wn/?utm_source=share&utm_medium=web2x&context=3)

```bash
Traceback (most recent call last):

File "E:\py\test-pygwalker\main.py", line 15, in <module>

gwalker = pyg.walk(df)

File "E:\py\test-pygwalker\venv\lib\site-packages\pygwalker\gwalker.py", line 91, in walk

js = render_gwalker_js(gid, props)

File "E:\py\test-pygwalker\venv\lib\site-packages\pygwalker\gwalker.py", line 65, in render_gwalker_js

js = gwalker_script() + js

File "E:\py\test-pygwalker\venv\lib\site-packages\pygwalker\base.py", line 15, in gwalker_script

gwalker_js = "const exports={};const process={env:{NODE_ENV:\"production\"} };" + f.read()

File "E:\Python\lib\encodings\cp1252.py", line 23, in decode

return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 511737: character maps to <undefined>
```

> even loading df = pd.DataFrame(data={'a':[1]}) causes this problem to appear.

**Comment by Asm-Def** [comment]
#9
