### ISSUE TITLE
Conda Installation ValueError: Could not parse spec

### ISSUE THREAD

**Issue by semmyk-research** [Kanaries/pygwalker#201]
gets `ValueError: Could not parse spec: hd43e919_0`
the error is practically the same for **`0.3.2`**, `0.3.1`, and `0.3.0`.

PS: install successfully on the same system and in the same conda env with
`pip install pygwalker==0.3.2`

[*step*]
1. `conda install -c conda-forge pygwalker` installed `pygwalker==0.2.1` by default!
2. attempt to install `conda install -c conda-forge pygwalker=0.3.2` results in a `duckdb` error
3. couldn't install with `conda install -c conda-forge python-duckdb pygwalker=0.3.2`, had to break into two steps.
4. Managed to get `conda install -c conda-forge python-duckdb=0.8.1` installed
5. Got stuck with `conda install -c conda-forge pygwalker=0.3.2`
6. Had no joy with `conda config --set solver classic, hence using `conda config --set solver libmamba` 
7. updated env to `python==3.11.4`, `conda==27.3.2`, `pydantic-core==2.1.1`, `dbduck==0.8.1`

[further info]
virtual packages : `__archspec=1=x86_64` | `__cuda=12.1=0` | `__win=0=0`  
user-agent : `conda/23.7.2 requests/2.31.0 CPython/3.11.4 Windows/10 Windows/10.0.17763 solver/libmamba conda-libmamba-solver/23.7.0 libmambapy/1.4.9`

[Error stack]
```
(streamlit) C:\Users\XXXYYY>conda install -c conda-forge pygwalker=0.3.0
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda_libmamba_solver\solver.py", line 575, in _str_to_matchspec
        name, version, build = spec.rsplit("-", 2)
        ^^^^^^^^^^^^^^^^^^^^
    ValueError: not enough values to unpack (expected 3, got 1)

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda\cli\main.py", line 64, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda\cli\conda_argparse.py", line 167, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda\notices\core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda\cli\main_install.py", line 26, in execute
        install(args, parser, "install")
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda\cli\install.py", line 316, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda\core\solve.py", line 154, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda\core\solve.py", line 215, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda_libmamba_solver\solver.py", line 215, in solve_final_state
        out_state = self._solving_loop(in_state, out_state, index)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda_libmamba_solver\solver.py", line 267, in _solving_loop
        solved = self._solve_attempt(in_state, out_state, index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda_libmamba_solver\solver.py", line 378, in _solve_attempt
        new_conflicts = self._maybe_raise_for_problems(problems, old_conflicts)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda_libmamba_solver\solver.py", line 635, in _maybe_raise_for_problems
        problems = self._parse_problems(problems)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda_libmamba_solver\solver.py", line 615, in _parse_problems
        conflicts.append(cls._str_to_matchspec(words[-1]))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\XxX\Anaconda3\envs\streamlit\Lib\site-packages\conda_libmamba_solver\solver.py", line 585, in _str_to_matchspec
        raise ValueError(f"Could not parse spec: {spec}") from exc
    ValueError: Could not parse spec: hd43e919_0

`$ C:\XxX\Anaconda3\envs\streamlit\Scripts\conda-script.py install -c conda-forge pygwalker=0.3.0`
```

**Comment by longxiaofei** [comment]
Thanks for feedback, my mistake.

I already fixed it(version 0.3.2).
