### ISSUE TITLE
Issue with Pygwalker

### ISSUE THREAD

**Issue by Aditi-Gupta2001** [Kanaries/pygwalker#555]
This is the error I am getting while trying to execute this code:
walker=pyg.walk(df)

Error:
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'BoxModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is
    at f.loadClass (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:75057)
    at f.loadModelClass (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:10729)
    at f._make_model (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:7517)
    at f.new_model (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:5137)
    at f.handle_comm_open (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:3894)
    at _handleCommOpen (http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:73473)
    at v._handleCommOpen (http://localhost:8889/static/notebook/3676.bundle.js:1:30808)
    at async v._handleMessage (http://localhost:8889/static/notebook/3676.bundle.js:1:32702)

**Comment by longxiaofei** [comment]
Hi @Aditi-Gupta2001 

This may be caused by version of jupyter extenstion.

You can try it:

```
pip install --upgrade jupyterlab
pip install --upgrade ipywidgets
```

Then restart your jupyter notebook.

**Comment by Aditi-Gupta2001** [comment]
It is not running these code in jupyter notebook

**Comment by longxiaofei** [comment]
If you want to update packages of python with notebook, you can run it in your notebook:

```
!pip install --upgrade jupyterlab
!pip install --upgrade ipywidgets
```

Then restart your jupyter notebook.

**Comment by Aditi-Gupta2001** [comment]
Thank You
